### ISSUE TITLE
Unknown license

### ISSUE THREAD

**Issue by Bluebugs** [LiraNuna/glsl-sse2#1]
Hello,

I am really interested by reusing your software, but I can't figure out the license of it. Is it GPL, LGPL, MIT or public domain like http://unlicense.org/ ? As you have all the code in headers, the license is very important to define the effect it will have on the application using it.

Thanks for your time

**Comment by LiraNuna** [comment]
I hope this isn't restrictive enough.
https://creativecommons.org/licenses/by/4.0/

Also, while I won't enforce you, it would be nice if you share bugs and fixes you made back to this project.

**Comment by Bluebugs** [comment]
This is disconcerting, I have never found any project software licensed under a CC license. There is always a first to everything :-). I can't find any online document explaining how to interact with that license when applied on software. If you want a license for software with assignment, the BSD-3-Clauses is more usual. Wouldn't it reflect your idea of what you expect from the CC BY 4.0 ? I don't mind the CC BY 4.0 at all, but could you explain what you would like someone using your software do in term of copyright notice and possible recompilation (it's just that I am not a lawyer and in front of license I am not used to all, I have no idea of your intention) ?

My software are usually a mix BSD-2-Clauses, GPL and LGPL (I am contributing to some library doing 2D and 3D graphism from enlightenment.org mostly). I don't want to use software in a way that their author would dislike I do prefer a healthy relationship as it is usually more productive for everyone. That's why I am trying to understand your intention here.

**Comment by LiraNuna** [comment]
The only difference between CC and BSD (as far as I'm aware) is that BSD is specific for software and CC is for any creative work (which includes software).
